[package]
name = "mdns"
version = "0.2.0"
authors = ["Paul Lietar <paul@lietar.net>"]

description = "Rust mDNS responder"
repository = "https://github.com/plietar/rust-mdns"
readme = "README.md"
license = "MIT"

[dependencies]
byteorder = "1.0"
futures = "0.1.6"
libc = "0.2"
log = "0.3"
multimap = "0.3"
net2 = "0.2"
nix = { git = "https://github.com/nix-rust/nix", branch = "new-ci/master" }
rand = "0.3"
tokio-core = "0.1.1"

dns-parser = { git = "https://github.com/plietar/dns-parser" }

[dev-dependencies]
env_logger = "0.4"
